(function() {
  window.SparkUkuleleLessons = [
    {
      id: "lesson_uke_orientation_01",
      title: "Meet the Ukulele",
      skill: "uke_orientation",
      level: 1,
      difficulty: "beginner",
      prerequisites: [],
      objectives: ["Name strings G-C-E-A", "Hold instrument comfortably"],
      exercises: ["ex_uke_orientation_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["orientation"],
      trackId: "track_uke_foundations",
      orderInTrack: 1
    },
    {
      id: "lesson_uke_tuning_01",
      title: "Tune G-C-E-A",
      skill: "uke_tuning",
      level: 1,
      difficulty: "beginner",
      prerequisites: ["lesson_uke_orientation_01"],
      objectives: ["Tune re-entrant GCEA", "Use tuner feedback calmly"],
      exercises: ["ex_uke_tuning_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["tuning"],
      trackId: "track_uke_foundations",
      orderInTrack: 2
    },
    {
      id: "lesson_uke_c6_sound_01",
      title: "The Open Ukulele Sound",
      skill: "uke_c6_sound",
      level: 1,
      difficulty: "beginner",
      prerequisites: ["lesson_uke_tuning_01"],
      objectives: ["Strum open strings", "Hear the C6 sound"],
      exercises: ["ex_uke_c6_sound_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["sound"],
      trackId: "track_uke_foundations",
      orderInTrack: 3
    },
    {
      id: "lesson_uke_down_strum_01",
      title: "First Down Strum",
      skill: "uke_down_strum",
      level: 1,
      difficulty: "beginner",
      prerequisites: ["lesson_uke_c6_sound_01"],
      objectives: ["Strum downward evenly", "Relax the wrist"],
      exercises: ["ex_uke_down_strum_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["rhythm", "strumming"],
      trackId: "track_uke_foundations",
      orderInTrack: 4
    },
    {
      id: "lesson_uke_count_quarters_01",
      title: "Count and Strum",
      skill: "uke_quarter_counting",
      level: 1,
      difficulty: "beginner",
      prerequisites: ["lesson_uke_down_strum_01"],
      objectives: ["Count 1-2-3-4", "Play with slow click"],
      exercises: ["ex_uke_count_quarters_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["rhythm"],
      trackId: "track_uke_foundations",
      orderInTrack: 5
    },
    {
      id: "lesson_uke_c_chord_01",
      title: "One-Finger C Chord",
      skill: "uke_c_chord",
      level: 1,
      difficulty: "beginner",
      prerequisites: ["lesson_uke_count_quarters_01"],
      objectives: ["Build C chord", "Play a C groove"],
      exercises: ["ex_uke_c_chord_01"],
      songs: ["song_uke_c_pulse_01"],
      masteryRequired: 0.75,
      tags: ["chord"],
      trackId: "track_uke_first_chords",
      orderInTrack: 1
    },
    {
      id: "lesson_uke_am_chord_01",
      title: "A Minor Chord",
      skill: "uke_am_chord",
      level: 1,
      difficulty: "beginner",
      prerequisites: ["lesson_uke_c_chord_01"],
      objectives: ["Build Am", "Compare C and Am feel"],
      exercises: ["ex_uke_am_chord_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["chord"],
      trackId: "track_uke_first_chords",
      orderInTrack: 2
    },
    {
      id: "lesson_uke_f_chord_01",
      title: "F Chord",
      skill: "uke_f_chord",
      level: 2,
      difficulty: "early_beginner",
      prerequisites: ["lesson_uke_am_chord_01"],
      objectives: ["Build F shape", "Keep second finger relaxed"],
      exercises: ["ex_uke_f_chord_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["chord"],
      trackId: "track_uke_first_chords",
      orderInTrack: 3
    },
    {
      id: "lesson_uke_g7_chord_01",
      title: "G7 Chord",
      skill: "uke_g7_chord",
      level: 2,
      difficulty: "early_beginner",
      prerequisites: ["lesson_uke_f_chord_01"],
      objectives: ["Build G7", "Hear pull back to C"],
      exercises: ["ex_uke_g7_chord_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["chord"],
      trackId: "track_uke_first_chords",
      orderInTrack: 4
    },
    {
      id: "lesson_uke_g_chord_01",
      title: "G Chord",
      skill: "uke_g_chord",
      level: 2,
      difficulty: "early_beginner",
      prerequisites: ["lesson_uke_g7_chord_01"],
      objectives: ["Build G", "Compare G and G7"],
      exercises: ["ex_uke_g_chord_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["chord"],
      trackId: "track_uke_first_chords",
      orderInTrack: 5
    },
    {
      id: "lesson_uke_first_two_chord_song_01",
      title: "First Two-Chord Ukulele Song",
      skill: "uke_two_chord_song",
      level: 2,
      difficulty: "early_beginner",
      prerequisites: ["lesson_uke_am_chord_01"],
      objectives: ["Switch C-Am", "Finish a tiny song loop"],
      exercises: ["ex_uke_first_two_chord_song_01"],
      songs: ["song_uke_c_am_easy_01"],
      masteryRequired: 0.75,
      tags: ["song"],
      trackId: "track_uke_first_chords",
      orderInTrack: 6
    },
    {
      id: "lesson_uke_c_am_switch_01",
      title: "C ↔ Am Switch",
      skill: "uke_chord_switching",
      level: 2,
      difficulty: "early_beginner",
      prerequisites: ["lesson_uke_first_two_chord_song_01"],
      objectives: ["Use one-finger movement", "Keep strumming hand moving"],
      exercises: ["ex_uke_c_am_switch_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["transition"],
      trackId: "track_uke_switching",
      orderInTrack: 1
    },
    {
      id: "lesson_uke_am_f_switch_01",
      title: "Am ↔ F Switch",
      skill: "uke_chord_switching",
      level: 2,
      difficulty: "early_beginner",
      prerequisites: ["lesson_uke_f_chord_01"],
      objectives: ["Use anchor finger", "Switch without rushing"],
      exercises: ["ex_uke_am_f_switch_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["transition"],
      trackId: "track_uke_switching",
      orderInTrack: 2
    },
    {
      id: "lesson_uke_f_g7_switch_01",
      title: "F ↔ G7 Switch",
      skill: "uke_chord_switching",
      level: 3,
      difficulty: "beginner_plus",
      prerequisites: ["lesson_uke_g7_chord_01"],
      objectives: ["Move three fingers slowly", "Use countdown assist"],
      exercises: ["ex_uke_f_g7_switch_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["transition"],
      trackId: "track_uke_switching",
      orderInTrack: 3
    },
    {
      id: "lesson_uke_four_chord_loop_01",
      title: "Four-Chord Uke Loop",
      skill: "uke_four_chord_loop",
      level: 3,
      difficulty: "beginner_plus",
      prerequisites: ["lesson_uke_c_am_switch_01", "lesson_uke_am_f_switch_01", "lesson_uke_f_g7_switch_01"],
      objectives: ["Play C-Am-F-G7", "Complete an 8-bar loop"],
      exercises: ["ex_uke_four_chord_loop_01"],
      songs: ["song_uke_c_am_f_g7_loop_01"],
      masteryRequired: 0.75,
      tags: ["progression"],
      trackId: "track_uke_switching",
      orderInTrack: 4
    },
    {
      id: "lesson_uke_eighth_strum_01",
      title: "Eighth Strum",
      skill: "uke_eighth_strum",
      level: 2,
      difficulty: "early_beginner",
      prerequisites: ["lesson_uke_count_quarters_01"],
      objectives: ["Count 1-and", "Keep light strums"],
      exercises: ["ex_uke_eighth_strum_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["rhythm"],
      trackId: "track_uke_strumming",
      orderInTrack: 1
    },
    {
      id: "lesson_uke_down_up_strum_01",
      title: "Down-Up Strum",
      skill: "uke_down_up_strum",
      level: 3,
      difficulty: "beginner_plus",
      prerequisites: ["lesson_uke_eighth_strum_01"],
      objectives: ["Alternate down/up", "Use small movement"],
      exercises: ["ex_uke_down_up_strum_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["rhythm"],
      trackId: "track_uke_strumming",
      orderInTrack: 2
    },
    {
      id: "lesson_uke_island_strum_01",
      title: "Island Strum",
      skill: "uke_island_strum",
      level: 3,
      difficulty: "beginner_plus",
      prerequisites: ["lesson_uke_down_up_strum_01", "lesson_uke_four_chord_loop_01"],
      objectives: ["Play D-DU-UDU", "Keep groove across chords"],
      exercises: ["ex_uke_island_strum_01"],
      songs: ["song_uke_island_loop_01"],
      masteryRequired: 0.75,
      tags: ["rhythm", "style"],
      trackId: "track_uke_strumming",
      orderInTrack: 3
    },
    {
      id: "lesson_uke_chuck_intro_01",
      title: "Chuck Intro",
      skill: "uke_chuck",
      level: 4,
      difficulty: "early_intermediate",
      prerequisites: ["lesson_uke_down_up_strum_01"],
      objectives: ["Create gentle percussive mute", "Do not over-squeeze"],
      exercises: ["ex_uke_chuck_intro_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["rhythm", "percussion"],
      trackId: "track_uke_strumming",
      orderInTrack: 4
    },
    {
      id: "lesson_uke_song_3_chord_01",
      title: "Three-Chord Song",
      skill: "uke_song",
      level: 3,
      difficulty: "beginner_plus",
      prerequisites: ["lesson_uke_f_g7_switch_01"],
      objectives: ["Play a verse loop", "Use assist on G7"],
      exercises: ["ex_uke_song_3_chord_01"],
      songs: ["song_uke_three_chord_01"],
      masteryRequired: 0.75,
      tags: ["song"],
      trackId: "track_uke_songs_picking_styles",
      orderInTrack: 1
    },
    {
      id: "lesson_uke_song_4_chord_01",
      title: "Four-Chord Song",
      skill: "uke_song",
      level: 4,
      difficulty: "early_intermediate",
      prerequisites: ["lesson_uke_island_strum_01"],
      objectives: ["Play a complete short song", "Review phrase stats"],
      exercises: ["ex_uke_song_4_chord_01"],
      songs: ["song_uke_four_chord_01"],
      masteryRequired: 0.75,
      tags: ["song"],
      trackId: "track_uke_songs_picking_styles",
      orderInTrack: 2
    },
    {
      id: "lesson_uke_phrase_retry_01",
      title: "Ukulele Phrase Retry",
      skill: "uke_phrase_retry",
      level: 4,
      difficulty: "early_intermediate",
      prerequisites: ["lesson_uke_song_4_chord_01"],
      objectives: ["Loop weakest phrase", "Improve chord change timing"],
      exercises: ["ex_uke_phrase_retry_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["performance", "phrase_retry"],
      trackId: "track_uke_songs_picking_styles",
      orderInTrack: 3
    },
    {
      id: "lesson_uke_fingerpicking_thumb_01",
      title: "Thumb Picking",
      skill: "uke_fingerpicking",
      level: 4,
      difficulty: "early_intermediate",
      prerequisites: ["lesson_uke_four_chord_loop_01"],
      objectives: ["Pick one string per beat", "Keep chord shape relaxed"],
      exercises: ["ex_uke_fingerpicking_thumb_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["picking"],
      trackId: "track_uke_songs_picking_styles",
      orderInTrack: 4
    },
    {
      id: "lesson_uke_fingerpicking_roll_01",
      title: "Fingerpicking Roll",
      skill: "uke_fingerpicking",
      level: 5,
      difficulty: "intermediate",
      prerequisites: ["lesson_uke_fingerpicking_thumb_01"],
      objectives: ["Play thumb-index-middle pattern", "Loop over C-Am-F-G7"],
      exercises: ["ex_uke_fingerpicking_roll_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["picking"],
      trackId: "track_uke_songs_picking_styles",
      orderInTrack: 5
    },
    {
      id: "lesson_uke_c_major_scale_01",
      title: "C Major Scale",
      skill: "uke_c_scale",
      level: 4,
      difficulty: "early_intermediate",
      prerequisites: ["lesson_uke_c_chord_01"],
      objectives: ["Play C scale on uke", "Use one-finger-per-fret idea"],
      exercises: ["ex_uke_c_major_scale_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["scale"],
      trackId: "track_uke_songs_picking_styles",
      orderInTrack: 6
    },
    {
      id: "lesson_uke_simple_melody_01",
      title: "Simple Melody",
      skill: "uke_melody",
      level: 4,
      difficulty: "early_intermediate",
      prerequisites: ["lesson_uke_c_major_scale_01"],
      objectives: ["Play a short melody", "Connect melody to chord sound"],
      exercises: ["ex_uke_simple_melody_01"],
      songs: ["song_uke_simple_melody_01"],
      masteryRequired: 0.75,
      tags: ["melody"],
      trackId: "track_uke_songs_picking_styles",
      orderInTrack: 7
    },
    {
      id: "lesson_uke_swing_strum_01",
      title: "Swing Strum",
      skill: "uke_styles",
      level: 5,
      difficulty: "intermediate",
      prerequisites: ["lesson_uke_down_up_strum_01"],
      objectives: ["Feel long-short eighths", "Play a relaxed swing groove"],
      exercises: ["ex_uke_swing_strum_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["style", "swing"],
      trackId: "track_uke_songs_picking_styles",
      orderInTrack: 8
    },
    {
      id: "lesson_uke_reggae_skank_01",
      title: "Reggae Skank Intro",
      skill: "uke_styles",
      level: 5,
      difficulty: "intermediate",
      prerequisites: ["lesson_uke_chuck_intro_01"],
      objectives: ["Play off-beat chords", "Mute spaces intentionally"],
      exercises: ["ex_uke_reggae_skank_01"],
      songs: [],
      masteryRequired: 0.75,
      tags: ["style", "reggae"],
      trackId: "track_uke_songs_picking_styles",
      orderInTrack: 9
    },
    {
      id: "lesson_uke_performance_set_01",
      title: "Ukulele Performance Set",
      skill: "uke_performance_set",
      level: 6,
      difficulty: "intermediate_plus",
      prerequisites: ["lesson_uke_phrase_retry_01", "lesson_uke_fingerpicking_roll_01"],
      objectives: ["Play three uke pieces", "Choose next style focus"],
      exercises: ["ex_uke_performance_set_01"],
      songs: ["set_uke_beginner_plus_01"],
      masteryRequired: 0.75,
      tags: ["performance"],
      trackId: "track_uke_songs_picking_styles",
      orderInTrack: 10
    }
  ];
})();
