(function() {
  window.PERFORMANCE_CHART_MANIFEST = {
    version: "2026-04-23",
    charts: [
      {
        id: "demo_progression",
        title: "Demo Progression",
        artist: "ChordSpark",
        bpm: 90,
        description: "ChordSpark demo chart with 8 steady chord hits.",
        sourceType: "built_in",
        accentColor: "#4ECDC4",
        badge: "Demo",
        instrument: "guitar"
      },
      {
        id: "demo_imported_package",
        title: "Imported MIDI Demo",
        artist: "SparkSuite Import",
        bpm: 120,
        description: "Package-backed import using notes.mid plus song.ini through SparkChartIO.",
        sourceType: "imported_package",
        accentColor: "#f59e0b",
        badge: "Import",
        instrument: "guitar"
      },
      {
        id: "three_little_birds_chords",
        title: "Three Little Birds",
        artist: "SparkSuite",
        bpm: 76,
        description: "Built-in chord performance chart from the song library.",
        sourceType: "built_in",
        accentColor: "#45B7D1",
        badge: "Song",
        instrument: "guitar"
      },
      {
        id: "riptide_chords",
        title: "Riptide",
        artist: "SparkSuite",
        bpm: 104,
        description: "Popular progression chart for rhythm-focused performance play.",
        sourceType: "built_in",
        accentColor: "#FF8A5C",
        badge: "Song",
        instrument: "guitar"
      },
      {
        id: "stand_by_me_chords",
        title: "Stand By Me",
        artist: "Ben E. King",
        bpm: 118,
        description: "Guitar chord highway for the classic I-vi-IV-V groove.",
        sourceType: "built_in",
        accentColor: "#14b8a6",
        badge: "Song",
        instrument: "guitar",
        songId: "stand_by_me",
        arrangementType: "chords"
      },
      {
        id: "stand_by_me_ukulele_chords",
        title: "Stand By Me",
        artist: "Ben E. King",
        bpm: 118,
        description: "Ukulele-specific chart with compact 4-string voicings and relaxed island-style changes.",
        sourceType: "built_in",
        accentColor: "#10b981",
        badge: "Ukulele",
        instrument: "ukulele",
        songId: "stand_by_me",
        arrangementType: "chords"
      },
      {
        id: "stand_by_me_piano_chords",
        title: "Stand By Me",
        artist: "Ben E. King",
        bpm: 118,
        description: "Piano-specific chart with left-hand roots leading into right-hand triad hits.",
        sourceType: "built_in",
        accentColor: "#0ea5e9",
        badge: "Piano",
        instrument: "piano",
        songId: "stand_by_me",
        arrangementType: "chords"
      },
      {
        id: "stand_by_me_bass_chords",
        title: "Stand By Me",
        artist: "Ben E. King",
        bpm: 118,
        description: "Bass-specific chart focused on the classic root-fifth pocket line.",
        sourceType: "built_in",
        accentColor: "#2563eb",
        badge: "Bass",
        instrument: "bass",
        songId: "stand_by_me",
        arrangementType: "chords"
      },
      {
        id: "la_bamba_chords",
        title: "La Bamba",
        artist: "Ritchie Valens",
        bpm: 156,
        description: "Guitar strum chart for the driving I-IV-V progression.",
        sourceType: "built_in",
        accentColor: "#f97316",
        badge: "Song",
        instrument: "guitar",
        songId: "la_bamba",
        arrangementType: "chords"
      },
      {
        id: "la_bamba_piano_chords",
        title: "La Bamba",
        artist: "Ritchie Valens",
        bpm: 156,
        description: "Piano-specific chart with alternating bass pickups into bright triad stabs.",
        sourceType: "built_in",
        accentColor: "#fb923c",
        badge: "Piano",
        instrument: "piano",
        songId: "la_bamba",
        arrangementType: "chords"
      },
      {
        id: "let_it_be_chords",
        title: "Let It Be",
        artist: "The Beatles",
        bpm: 75,
        description: "Guitar chord progression for the ballad-style verse and chorus flow.",
        sourceType: "built_in",
        accentColor: "#60a5fa",
        badge: "Song",
        instrument: "guitar",
        songId: "let_it_be",
        arrangementType: "chords"
      },
      {
        id: "let_it_be_piano_chords",
        title: "Let It Be",
        artist: "The Beatles",
        bpm: 75,
        description: "Piano-specific chart with root pickups into fuller triad voicings.",
        sourceType: "built_in",
        accentColor: "#3b82f6",
        badge: "Piano",
        instrument: "piano",
        songId: "let_it_be",
        arrangementType: "chords"
      },
      {
        id: "knockin_on_heavens_door_chords",
        title: "Knockin' on Heaven's Door",
        artist: "Bob Dylan",
        bpm: 69,
        description: "Guitar chart for the laid-back four-chord folk progression.",
        sourceType: "built_in",
        accentColor: "#f59e0b",
        badge: "Song",
        instrument: "guitar",
        songId: "knockin_on_heavens_door",
        arrangementType: "chords"
      },
      {
        id: "knockin_on_heavens_door_piano_chords",
        title: "Knockin' on Heaven's Door",
        artist: "Bob Dylan",
        bpm: 69,
        description: "Piano-specific chart with root lead-ins and held block-chord voicings.",
        sourceType: "built_in",
        accentColor: "#fbbf24",
        badge: "Piano",
        instrument: "piano",
        songId: "knockin_on_heavens_door",
        arrangementType: "chords"
      },
      {
        id: "with_or_without_you_chords",
        title: "With or Without You",
        artist: "U2",
        bpm: 110,
        description: "Steady four-chord anthem loop for rhythm endurance practice.",
        sourceType: "built_in",
        accentColor: "#60a5fa",
        badge: "Song",
        instrument: "guitar",
        songId: "with_or_without_you",
        arrangementType: "chords"
      },
      {
        id: "with_or_without_you_bass_chords",
        title: "With or Without You",
        artist: "U2",
        bpm: 110,
        description: "Bass-specific chart built around sustained whole-note roots and pulse control.",
        sourceType: "built_in",
        accentColor: "#1d4ed8",
        badge: "Bass",
        instrument: "bass",
        songId: "with_or_without_you",
        arrangementType: "chords"
      },
      {
        id: "zombie_chords",
        title: "Zombie",
        artist: "The Cranberries",
        bpm: 84,
        description: "Driving alt-rock chord loop with spacious one-bar changes.",
        sourceType: "built_in",
        accentColor: "#f97316",
        badge: "Song",
        instrument: "guitar",
        songId: "zombie",
        arrangementType: "chords"
      },
      {
        id: "zombie_bass_chords",
        title: "Zombie",
        artist: "The Cranberries",
        bpm: 84,
        description: "Bass-specific chart focused on the grounded low-end pulse under the alt-rock loop.",
        sourceType: "built_in",
        accentColor: "#ea580c",
        badge: "Bass",
        instrument: "bass",
        songId: "zombie",
        arrangementType: "chords"
      },
      {
        id: "smells_like_teen_spirit_chords",
        title: "Smells Like Teen Spirit",
        artist: "Nirvana",
        bpm: 117,
        description: "Power-chord highway focused on the iconic grunge progression.",
        sourceType: "built_in",
        accentColor: "#eab308",
        badge: "Song",
        instrument: "guitar",
        songId: "smells_like_teen_spirit",
        arrangementType: "chords"
      },
      {
        id: "smells_like_teen_spirit_bass_chords",
        title: "Smells Like Teen Spirit",
        artist: "Nirvana",
        bpm: 117,
        description: "Bass-specific chart with pumping eighth-note roots and verse-to-chorus drive.",
        sourceType: "built_in",
        accentColor: "#ca8a04",
        badge: "Bass",
        instrument: "bass",
        songId: "smells_like_teen_spirit",
        arrangementType: "chords"
      },
      {
        id: "billie_jean_bass_chords",
        title: "Billie Jean",
        artist: "Michael Jackson",
        bpm: 117,
        description: "Bass-specific chart built around the iconic syncopated pop riff.",
        sourceType: "built_in",
        accentColor: "#7c3aed",
        badge: "Bass",
        instrument: "bass",
        songId: "billie_jean",
        arrangementType: "chords"
      },
      {
        id: "come_together_bass_chords",
        title: "Come Together",
        artist: "The Beatles",
        bpm: 83,
        description: "Bass-specific chart for the slinky riff-led verse groove.",
        sourceType: "built_in",
        accentColor: "#475569",
        badge: "Bass",
        instrument: "bass",
        songId: "come_together",
        arrangementType: "chords"
      },
      {
        id: "feel_good_inc_bass_chords",
        title: "Feel Good Inc",
        artist: "Gorillaz",
        bpm: 138,
        description: "Bass-specific chart with chromatic riff movement and tight looped pocket.",
        sourceType: "built_in",
        accentColor: "#334155",
        badge: "Bass",
        instrument: "bass",
        songId: "feel_good_inc",
        arrangementType: "chords"
      },
      {
        id: "another_one_bites_the_dust_bass_chords",
        title: "Another One Bites the Dust",
        artist: "Queen",
        bpm: 110,
        description: "Bass-specific chart for the signature octave-driving riff.",
        sourceType: "built_in",
        accentColor: "#991b1b",
        badge: "Bass",
        instrument: "bass",
        songId: "another_one_bites_the_dust",
        arrangementType: "chords"
      },
      {
        id: "seven_nation_army_bass_chords",
        title: "Seven Nation Army",
        artist: "The White Stripes",
        bpm: 123,
        description: "Bass-specific chart for the iconic single-string-style riff translated to low end.",
        sourceType: "built_in",
        accentColor: "#b91c1c",
        badge: "Bass",
        instrument: "bass",
        songId: "seven_nation_army",
        arrangementType: "chords"
      },
      {
        id: "longview_bass_chords",
        title: "Longview",
        artist: "Green Day",
        bpm: 112,
        description: "Bass-specific chart centered on the rolling verse riff and sustained pocket.",
        sourceType: "built_in",
        accentColor: "#0f766e",
        badge: "Bass",
        instrument: "bass",
        songId: "longview",
        arrangementType: "chords"
      },
      {
        id: "under_pressure_bass_chords",
        title: "Under Pressure",
        artist: "Queen & David Bowie",
        bpm: 114,
        description: "Bass-specific chart for the instantly recognizable repeating hook.",
        sourceType: "built_in",
        accentColor: "#1e3a8a",
        badge: "Bass",
        instrument: "bass",
        songId: "under_pressure",
        arrangementType: "chords"
      },
      {
        id: "pumped_up_kicks_chords",
        title: "Pumped Up Kicks",
        artist: "Foster the People",
        bpm: 128,
        description: "Tight indie-pop four-chord loop for steady groove practice.",
        sourceType: "built_in",
        accentColor: "#34d399",
        badge: "Song",
        instrument: "guitar",
        songId: "pumped_up_kicks",
        arrangementType: "chords"
      },
      {
        id: "pumped_up_kicks_bass_chords",
        title: "Pumped Up Kicks",
        artist: "Foster the People",
        bpm: 128,
        description: "Bass-specific chart with syncopated root movement and tighter low-end pickups.",
        sourceType: "built_in",
        accentColor: "#0f766e",
        badge: "Bass",
        instrument: "bass",
        songId: "pumped_up_kicks",
        arrangementType: "chords"
      },
      {
        id: "ukulele_island_package",
        title: "Island Loop",
        artist: "SparkSuite Ukulele",
        bpm: 78,
        description: "Ukulele package-backed performance chart with a 4-string lane layout.",
        sourceType: "imported_package",
        accentColor: "#22c55e",
        badge: "Ukulele",
        instrument: "ukulele"
      },
      {
        id: "ukulele_switch_flow_package",
        title: "Sunset Switches",
        artist: "SparkSuite Ukulele",
        bpm: 74,
        description: "Ukulele chord-switching performance chart with a fuller 16-beat loop.",
        sourceType: "imported_package",
        accentColor: "#16a34a",
        badge: "Ukulele",
        instrument: "ukulele"
      },
      {
        id: "ukulele_moonlit_picking_package",
        title: "Moonlit Picking",
        artist: "SparkSuite Ukulele",
        bpm: 72,
        description: "Ukulele fingerpicking performance chart with a 4-string arpeggio pattern.",
        sourceType: "imported_package",
        accentColor: "#0f766e",
        badge: "Ukulele",
        instrument: "ukulele"
      },
      {
        id: "bass_midnight_lock_package",
        title: "Midnight Lock",
        artist: "SparkSuite Bass",
        bpm: 75,
        description: "Bass package-backed performance chart with a steady 4-string pocket groove.",
        sourceType: "imported_package",
        accentColor: "#2563eb",
        badge: "Bass",
        instrument: "bass"
      },
      {
        id: "bass_afterglow_walk_package",
        title: "Afterglow Walk",
        artist: "SparkSuite Bass",
        bpm: 71,
        description: "Bass package-backed walking chart with a more melodic 4-string line.",
        sourceType: "imported_package",
        accentColor: "#1d4ed8",
        badge: "Bass",
        instrument: "bass"
      }
    ]
  };
})();
