(function() {
  window.SparkGuitarSkillTree = [
    { id: "guitar_orientation", name: "Guitar Orientation", category: "fundamentals", prerequisites: [] },
    { id: "guitar_tuning", name: "Tuning", category: "fundamentals", prerequisites: ["guitar_orientation"] },
    { id: "open_strings", name: "Open Strings", category: "fundamentals", prerequisites: ["guitar_tuning"] },
    { id: "pick_downstrokes", name: "Pick Downstrokes", category: "rhythm", prerequisites: ["open_strings"] },
    { id: "quarter_counting", name: "Quarter-Note Counting", category: "rhythm", prerequisites: ["pick_downstrokes"] },
    { id: "first_riff", name: "First Open-String Riff", category: "performance", prerequisites: ["quarter_counting"] },
    { id: "em_chord", name: "E Minor Chord", category: "chords", prerequisites: ["quarter_counting"] },
    { id: "g_chord", name: "G Chord", category: "chords", prerequisites: ["em_chord"] },
    { id: "c_chord", name: "C Chord", category: "chords", prerequisites: ["g_chord"] },
    { id: "d_chord", name: "D Chord", category: "chords", prerequisites: ["g_chord"] },
    { id: "am_chord", name: "A Minor Chord", category: "chords", prerequisites: ["c_chord"] },
    { id: "open_chord_switching", name: "Open Chord Switching", category: "transitions", prerequisites: ["em_chord", "g_chord"] },
    { id: "four_chord_loop", name: "Four-Chord Loop", category: "progressions", prerequisites: ["open_chord_switching", "c_chord", "d_chord"] },
    { id: "eighth_strumming", name: "Eighth-Note Strumming", category: "rhythm", prerequisites: ["quarter_counting"] },
    { id: "down_up_strumming", name: "Down-Up Strumming", category: "rhythm", prerequisites: ["eighth_strumming"] },
    { id: "muted_strumming", name: "Muted Strumming", category: "rhythm", prerequisites: ["down_up_strumming"] },
    { id: "song_phrase_retry", name: "Phrase Retry", category: "performance", prerequisites: ["four_chord_loop"] },
    { id: "power_chords", name: "Power Chords", category: "chords", prerequisites: ["open_chord_switching"] },
    { id: "barre_intro", name: "Barre Chord Intro", category: "chords", prerequisites: ["power_chords"] },
    { id: "minor_pentatonic", name: "Minor Pentatonic", category: "lead", prerequisites: ["open_strings"] },
    { id: "single_note_timing", name: "Single-Note Timing", category: "lead", prerequisites: ["minor_pentatonic"] },
    { id: "fingerstyle_pima", name: "Fingerstyle PIMA", category: "fingerstyle", prerequisites: ["open_chord_switching"] },
    { id: "caged_intro", name: "CAGED Intro", category: "fretboard", prerequisites: ["barre_intro"] },
    { id: "triads_intro", name: "Triads Intro", category: "fretboard", prerequisites: ["caged_intro"] },
    { id: "performance_set", name: "Performance Set", category: "performance", prerequisites: ["song_phrase_retry"] },
    { id: "e_a_chords", name: "E and A Chords", category: "chords", prerequisites: [] },
    { id: "syncopation_intro", name: "Syncopation Intro", category: "rhythm", prerequisites: [] },
    { id: "two_chord_song", name: "Two-Chord Song", category: "performance", prerequisites: [] },
    { id: "four_chord_song", name: "Four-Chord Song", category: "performance", prerequisites: [] },
    { id: "song_performance", name: "Song Performance", category: "performance", prerequisites: [] },
    { id: "bend_slide_intro", name: "Bends and Slides Intro", category: "lead", prerequisites: [] }
  ];
})();
