(function() {
  window.SparkGuitarLessons = [
    { id: "lesson_gtr_01", num: 1, level: 1, title: "Guitar orientation", skill: "gtr_orientation", prerequisites: [], masteryRequired: 0, desc: "Name the guitar parts, rest position, and one tiny start ritual.", objectives: ["Hold the guitar comfortably", "Identify strings and frets", "Start with a 2-bar count-in"] },
    { id: "lesson_gtr_02", num: 2, level: 1, title: "Tune before playing", skill: "gtr_tuning", prerequisites: ["lesson_gtr_01"], masteryRequired: 0.4, desc: "Check tuning and hear when a string is too high or low.", objectives: ["Tune one string", "Match pitch direction", "Reset posture"] },
    { id: "lesson_gtr_03", num: 3, level: 1, title: "Pick hold", skill: "gtr_pick_hold", prerequisites: ["lesson_gtr_02"], masteryRequired: 0.4, desc: "Hold the pick with relaxed pressure and a short motion path.", objectives: ["Relax thumb and index", "Use small movements", "Avoid arm tension"] },
    { id: "lesson_gtr_04", num: 4, level: 1, title: "Open-string pulse", skill: "gtr_open_strum", prerequisites: ["lesson_gtr_03"], masteryRequired: 0.45, desc: "Play open strings with a steady quarter-note pulse.", objectives: ["Strum open strings", "Stay with 60 BPM", "Stop cleanly"] },
    { id: "lesson_gtr_05", num: 5, level: 1, title: "Down strum", skill: "gtr_down_strum", prerequisites: ["lesson_gtr_04"], masteryRequired: 0.5, desc: "Use consistent down-strums across 8 bars.", objectives: ["Count 1-2-3-4", "Strum down on each beat", "Track clean tempo"] },
    { id: "lesson_gtr_06", num: 6, level: 1, title: "Quarter-note counting", skill: "gtr_quarter_counting", prerequisites: ["lesson_gtr_05"], masteryRequired: 0.5, desc: "Connect rhythm counting to the strumming hand.", objectives: ["Say the count", "Play the count", "Notice drift"] },
    { id: "lesson_gtr_07", num: 7, level: 2, title: "E minor chord", skill: "gtr_em_chord", prerequisites: ["lesson_gtr_06"], masteryRequired: 0.55, desc: "Build the first easy chord shape and strum it cleanly.", objectives: ["Place two fingers", "Check muted strings", "Play 8 clean pulses"] },
    { id: "lesson_gtr_08", num: 8, level: 2, title: "G chord", skill: "gtr_g_chord", prerequisites: ["lesson_gtr_07"], masteryRequired: 0.55, desc: "Build a G chord shape with slow placement and clean tone.", objectives: ["Place fingers in order", "Check buzzes", "Play slow pulses"] },
    { id: "lesson_gtr_09", num: 9, level: 2, title: "C chord", skill: "gtr_c_chord", prerequisites: ["lesson_gtr_08"], masteryRequired: 0.55, desc: "Learn the C shape as a visual pattern, not a memorization task.", objectives: ["Find the root area", "Place the shape", "Strum slowly"] },
    { id: "lesson_gtr_10", num: 10, level: 2, title: "D chord", skill: "gtr_d_chord", prerequisites: ["lesson_gtr_09"], masteryRequired: 0.55, desc: "Play the compact D triangle shape with clean top strings.", objectives: ["Build the triangle", "Avoid low strings", "Pulse 8 bars"] },
    { id: "lesson_gtr_11", num: 11, level: 3, title: "Chord switching", skill: "gtr_chord_switching", prerequisites: ["lesson_gtr_10"], masteryRequired: 0.6, desc: "Switch between two chords using one shared anchor idea.", objectives: ["Move on beat 4", "Land before beat 1", "Keep tempo slow"] },
    { id: "lesson_gtr_12", num: 12, level: 3, title: "Two-chord song loop", skill: "gtr_two_chord_song", prerequisites: ["lesson_gtr_11"], masteryRequired: 0.6, desc: "Turn two chords into a short playable loop.", objectives: ["Play 4 bars", "Repeat without stopping", "Log last clean BPM"] },
    { id: "lesson_gtr_13", num: 13, level: 3, title: "Four-chord loop", skill: "gtr_four_chord_loop", prerequisites: ["lesson_gtr_12"], masteryRequired: 0.62, desc: "Play a simple four-chord progression as a repeating pattern.", objectives: ["Recognize the loop", "Keep one strum pattern", "Finish 8 bars"] },
    { id: "lesson_gtr_14", num: 14, level: 4, title: "Eighth-note strum", skill: "gtr_eighth_strum", prerequisites: ["lesson_gtr_13"], masteryRequired: 0.62, desc: "Feel two smaller pulses inside each beat.", objectives: ["Count 1-and", "Keep hand moving", "Stay relaxed"] },
    { id: "lesson_gtr_15", num: 15, level: 4, title: "Down-up strum", skill: "gtr_down_up_strum", prerequisites: ["lesson_gtr_14"], masteryRequired: 0.65, desc: "Add up-strums without changing the beat grid.", objectives: ["Down on numbers", "Up on ands", "Loop 30 seconds"] },
    { id: "lesson_gtr_16", num: 16, level: 4, title: "Accent strum", skill: "gtr_accent_strum", prerequisites: ["lesson_gtr_15"], masteryRequired: 0.65, desc: "Make beat 2 or 4 louder while the hand keeps moving.", objectives: ["Accent one beat", "Keep other beats quiet", "Avoid rushing"] },
    { id: "lesson_gtr_17", num: 17, level: 5, title: "Muting", skill: "gtr_muting", prerequisites: ["lesson_gtr_16"], masteryRequired: 0.68, desc: "Stop sound intentionally with fretting and strumming hand control.", objectives: ["Mute after strum", "Create a short rest", "Control noise"] },
    { id: "lesson_gtr_18", num: 18, level: 5, title: "Fingerpicking pattern", skill: "gtr_fingerpicking", prerequisites: ["lesson_gtr_17"], masteryRequired: 0.68, desc: "Pick a simple string pattern with steady timing.", objectives: ["Assign fingers", "Pick 4-note loop", "Stay even"] },
    { id: "lesson_gtr_19", num: 19, level: 6, title: "G major scale", skill: "gtr_g_major_scale", prerequisites: ["lesson_gtr_18"], masteryRequired: 0.7, desc: "Use a scale as a visual path across the strings.", objectives: ["Play ascending", "Play descending", "Hear stepwise motion"] },
    { id: "lesson_gtr_20", num: 20, level: 6, title: "Simple melody", skill: "gtr_melody", prerequisites: ["lesson_gtr_19"], masteryRequired: 0.7, desc: "Turn scale notes into a short melody phrase.", objectives: ["Play 4 notes", "Repeat a phrase", "End on home note"] },
    { id: "lesson_gtr_21", num: 21, level: 7, title: "Power chords", skill: "gtr_power_chords", prerequisites: ["lesson_gtr_20"], masteryRequired: 0.72, desc: "Play two-note power chord shapes with clean rhythm.", objectives: ["Find root", "Add fifth", "Move shape"] },
    { id: "lesson_gtr_22", num: 22, level: 7, title: "Barre intro", skill: "gtr_barre_intro", prerequisites: ["lesson_gtr_21"], masteryRequired: 0.72, desc: "Start barre technique with pressure management and partial shapes.", objectives: ["Use side of finger", "Avoid squeezing", "Play partial barre"] },
    { id: "lesson_gtr_23", num: 23, level: 8, title: "Song run", skill: "gtr_song", prerequisites: ["lesson_gtr_22"], masteryRequired: 0.75, desc: "Play a structured song-form practice run.", objectives: ["Start cleanly", "Recover from mistakes", "Finish the form"] },
    { id: "lesson_gtr_24", num: 24, level: 8, title: "Phrase retry", skill: "gtr_phrase_retry", prerequisites: ["lesson_gtr_23"], masteryRequired: 0.75, desc: "Loop the hardest phrase until it becomes stable.", objectives: ["Find weak phrase", "Repeat slowly", "Increase tempo only after stability"] },
    { id: "lesson_gtr_25", num: 25, level: 8, title: "Performance set", skill: "gtr_performance_set", prerequisites: ["lesson_gtr_24"], masteryRequired: 0.8, desc: "Combine chords, rhythm, melody, and recovery into a confident set.", objectives: ["Play complete run", "Log result", "Pick next target"] }
  ];
})();
