// The public-domain MIDI arrangements (ode_to_joy.mid, amazing_grace.mid)
// are generated by scripts/songs/generate_public_domain_midis.js and are
// the only corpus files covered by the repository's MIT license. Pin that
// they exist, parse with the core SparkChartIO parser, and carry the
// expected melodies so a regeneration can't silently corrupt them.
var assert = require("assert");
var fs = require("fs");
var path = require("path");

var passed = 0;
var failed = 0;

function test(name, fn) {
  try {
    fn();
    passed++;
    console.log("  PASS: " + name);
  } catch (err) {
    failed++;
    console.error("  FAIL: " + name);
    console.error("    " + err.message);
  }
}

global.window = global;
eval(fs.readFileSync(path.join(__dirname, "..", "js/sparksuite/core/chart_io.js"), "utf8"));

function parseCorpusMidi(id) {
  var buffer = fs.readFileSync(path.join(__dirname, "..", "content", "songs", "midi", id + ".mid"));
  return new window.SparkChartIO().parseMidiRaw(buffer);
}

console.log("=== Public-Domain MIDI Arrangement Tests ===");

test("ode_to_joy.mid parses with the correct musical skeleton", function() {
  var raw = parseCorpusMidi("ode_to_joy");
  assert.strictEqual(raw.ppq, 480);
  assert.deepStrictEqual(raw.tempoSegments, [{ tick: 0, bpm: 90 }]);
  assert.deepStrictEqual(raw.timeSignatures, [{ tick: 0, numerator: 4, denominator: 4 }]);
  assert.strictEqual(raw.lastTickEnd, 16 * 4 * 480, "16 bars of 4/4");

  var melody = raw.tracks.find(function(t) { return t.name === "Melody RH"; });
  var bass = raw.tracks.find(function(t) { return t.name === "Bass LH"; });
  assert.ok(melody && bass, "melody and bass tracks present");

  // Theme opening: E E F G | G F E D (E4=64)
  assert.deepStrictEqual(
    melody.notes.slice(0, 8).map(function(x) { return x.midi; }),
    [64, 64, 65, 67, 67, 65, 64, 62]
  );
  // Right hand stays in the C five-finger position taught by the piano
  // curriculum (C4-G4), except the low G3 cadence in the B phrase.
  melody.notes.forEach(function(note) {
    assert.ok(note.midi === 55 || (note.midi >= 60 && note.midi <= 67), "unexpected pitch " + note.midi);
  });
});

test("amazing_grace.mid parses with the traditional NEW BRITAIN melody", function() {
  var raw = parseCorpusMidi("amazing_grace");
  assert.strictEqual(raw.ppq, 480);
  assert.deepStrictEqual(raw.tempoSegments, [{ tick: 0, bpm: 80 }]);
  assert.deepStrictEqual(raw.timeSignatures, [{ tick: 0, numerator: 3, denominator: 4 }]);

  var melody = raw.tracks.find(function(t) { return t.name === "Melody RH"; });
  assert.ok(melody, "melody track present");

  // Pickup + first phrase: G3 | C4 E4-C4 | E4 D4 | C4 A3 | G3 G3
  assert.deepStrictEqual(
    melody.notes.slice(0, 10).map(function(x) { return x.midi; }),
    [55, 60, 64, 60, 64, 62, 60, 57, 55, 55]
  );
  // NEW BRITAIN is pentatonic: C D E G A only, G3-G4.
  var allowed = { 55: 1, 57: 1, 60: 1, 62: 1, 64: 1, 67: 1 };
  melody.notes.forEach(function(note) {
    assert.ok(allowed[note.midi], "non-pentatonic pitch " + note.midi);
  });
  // The tune peaks on "me" (G4) held for a full bar plus a half note.
  var peak = melody.notes.filter(function(x) { return x.midi === 67; });
  assert.ok(peak.length >= 3, "expected the G4 peak notes");
});

test("generator is deterministic (regeneration produces identical bytes)", function() {
  var dir = path.join(__dirname, "..", "content", "songs", "midi");
  var before = {
    ode: fs.readFileSync(path.join(dir, "ode_to_joy.mid")),
    ag: fs.readFileSync(path.join(dir, "amazing_grace.mid"))
  };
  var cp = require("child_process");
  cp.execFileSync(process.execPath, [path.join(__dirname, "..", "scripts", "songs", "generate_public_domain_midis.js")], { stdio: "pipe" });
  assert.ok(before.ode.equals(fs.readFileSync(path.join(dir, "ode_to_joy.mid"))), "ode_to_joy.mid changed on regeneration");
  assert.ok(before.ag.equals(fs.readFileSync(path.join(dir, "amazing_grace.mid"))), "amazing_grace.mid changed on regeneration");
});

if (failed > 0) process.exitCode = 1;
console.log("\n" + passed + " passed, " + failed + " failed");
