// The chords-only personal-use backings (mad_world.mid,
// you_are_my_sunshine.mid) are generated by
// scripts/songs/generate_personal_use_backings.js. Pin that they parse
// with the core SparkChartIO parser, stay chords-only (no melody track),
// and regenerate byte-identically.
var assert = require("assert");
var fs = require("fs");
var path = require("path");

var passed = 0;
var failed = 0;

function test(name, fn) {
  try {
    fn();
    passed++;
    console.log("  PASS: " + name);
  } catch (err) {
    failed++;
    console.error("  FAIL: " + name);
    console.error("    " + err.message);
  }
}

global.window = global;
eval(fs.readFileSync(path.join(__dirname, "..", "js/sparksuite/core/chart_io.js"), "utf8"));

function parseCorpusMidi(id) {
  var buffer = fs.readFileSync(path.join(__dirname, "..", "content", "songs", "midi", id + ".mid"));
  return new window.SparkChartIO().parseMidiRaw(buffer);
}

function pitchClasses(track) {
  var classes = {};
  track.notes.forEach(function(note) { classes[note.midi % 12] = true; });
  return Object.keys(classes).map(Number).sort(function(a, b) { return a - b; });
}

console.log("=== Generated Backing MIDI Tests ===");

test("mad_world.mid is a 16-bar Dm-F-C-G chords-only backing", function() {
  var raw = parseCorpusMidi("mad_world");
  assert.deepStrictEqual(raw.tempoSegments, [{ tick: 0, bpm: 88 }]);
  assert.strictEqual(raw.lastTickEnd, 16 * 4 * 480);

  var names = raw.tracks.map(function(t) { return t.name; });
  assert.ok(names.indexOf("Chords") >= 0 && names.indexOf("Bass Roots") >= 0);
  assert.strictEqual(names.filter(function(x) { return /melody/i.test(x); }).length, 0,
    "backings must stay chords-only");

  // Dm F C G harmonic content only: D F A / F A C / C E G / G B D
  var chords = raw.tracks.find(function(t) { return t.name === "Chords"; });
  assert.deepStrictEqual(pitchClasses(chords), [0, 2, 4, 5, 7, 9, 11]);
  var bass = raw.tracks.find(function(t) { return t.name === "Bass Roots"; });
  assert.deepStrictEqual(pitchClasses(bass), [0, 2, 5, 7], "roots D F C G only");
});

test("you_are_my_sunshine.mid is a 16-bar C-F-G7 chords-only backing", function() {
  var raw = parseCorpusMidi("you_are_my_sunshine");
  assert.deepStrictEqual(raw.tempoSegments, [{ tick: 0, bpm: 100 }]);
  assert.strictEqual(raw.lastTickEnd, 16 * 4 * 480);

  var chords = raw.tracks.find(function(t) { return t.name === "Chords"; });
  var bass = raw.tracks.find(function(t) { return t.name === "Bass Roots"; });
  assert.ok(chords && bass);
  // C E G / F A C / G B D F
  assert.deepStrictEqual(pitchClasses(chords), [0, 2, 4, 5, 7, 9, 11]);
  assert.deepStrictEqual(pitchClasses(bass), [0, 5, 7], "roots C F G only");
});

test("generator is deterministic (regeneration produces identical bytes)", function() {
  var dir = path.join(__dirname, "..", "content", "songs", "midi");
  var before = {
    mw: fs.readFileSync(path.join(dir, "mad_world.mid")),
    ys: fs.readFileSync(path.join(dir, "you_are_my_sunshine.mid"))
  };
  var cp = require("child_process");
  cp.execFileSync(process.execPath, [path.join(__dirname, "..", "scripts", "songs", "generate_personal_use_backings.js")], { stdio: "pipe" });
  assert.ok(before.mw.equals(fs.readFileSync(path.join(dir, "mad_world.mid"))), "mad_world.mid changed on regeneration");
  assert.ok(before.ys.equals(fs.readFileSync(path.join(dir, "you_are_my_sunshine.mid"))), "you_are_my_sunshine.mid changed on regeneration");
});

if (failed > 0) process.exitCode = 1;
console.log("\n" + passed + " passed, " + failed + " failed");
