#!/usr/bin/env node
// scripts/apply_generated_instrument.js
// Full integration: rebuilds manifest, updates index.html, updates test file, validates.
// Usage: node scripts/apply_generated_instrument.js [--skip-validate]

var fs = require("fs");
var path = require("path");
var NL = String.fromCharCode(10);
var Q = String.fromCharCode(34);
function q(s) { return Q + s + Q; }

var skipValidate = process.argv.indexOf("--skip-validate") >= 0;
var rtDir = "js/instruments";
var ssDir = "js/sparksuite/instruments";

// ── Step 1: Scan instruments ──
console.log("Step 1: Scanning instruments...");

function extractField(code, field) {
  var idx = code.indexOf(field);
  if (idx < 0) return null;
  var rest = code.substring(idx + field.length);
  var m = rest.match(/["']([^"']+)/);
  return m ? m[1] : null;
}

var sparkSuiteOrder = ["skill_tree","bass_module","bass_curriculum_integration","curriculum","lessons","chords","scales","tuning","exercises","patterns","songs","kits","mapping","notation","progression","packs","bass_adapter","piano_adapter","guitar_adapter","chart_library","rhythm_curriculum","runtime_adapter","rhythm_adapter","module","adapter","index"];
var runtimeOrder = ["data","audio","ui","watch","pages","capo","chord_normalizer","validator","ukulele_svg","register","app"];

function orderIndex(file, order) {
  for (var i = 0; i < order.length; i++) {
    if (file.indexOf(order[i]) >= 0) return i;
  }
  return order.length;
}

function sortByKnownOrder(a, b, order) {
  var ai = orderIndex(a, order);
  var bi = orderIndex(b, order);
  if (ai !== bi) return ai - bi;
  return a.localeCompare(b);
}

var dirs = fs.readdirSync(rtDir).filter(function(d) {
  var full = path.join(rtDir, d);
  return fs.statSync(full).isDirectory() && fs.existsSync(path.join(full, "register.js"));
});

var instruments = [];
dirs.forEach(function(dir) {
  var code = fs.readFileSync(path.join(rtDir, dir, "register.js"), "utf8");
  var id = extractField(code, "id:");
  var inst = extractField(code, "instrument:") || dir;
  if (!id) return;

  var scripts = [];
  var ssPath = path.join(ssDir, dir);
  if (fs.existsSync(ssPath)) {
    var ssFiles = fs.readdirSync(ssPath).filter(function(f) { return f.endsWith(".js"); });
    ssFiles.sort(function(a, b) { return sortByKnownOrder(a, b, sparkSuiteOrder); });
    ssFiles.forEach(function(f) { scripts.push(ssDir + "/" + dir + "/" + f); });
  }

  var rtFiles = fs.readdirSync(path.join(rtDir, dir)).filter(function(f) { return f.endsWith(".js"); });
  rtFiles.sort(function(a, b) { return sortByKnownOrder(a, b, runtimeOrder); });
  rtFiles.forEach(function(f) { scripts.push(rtDir + "/" + dir + "/" + f); });
  instruments.push({ id: id, instrument: inst, dir: dir, scripts: scripts });
  console.log("  Found: " + id + " (" + inst + ") - " + scripts.length + " scripts");
});
console.log("  Total: " + instruments.length + " instruments");

function runtimeScriptsForInstrument(inst) {
  return inst.scripts.filter(function(src) {
    return src.indexOf(rtDir + "/" + inst.dir + "/") === 0;
  });
}

// ── Step 2: Write manifest ──
console.log("");
console.log("Step 2: Writing manifest...");

var manifestLines = [];
manifestLines.push("// AUTO-GENERATED by apply_generated_instrument.js");
manifestLines.push("// Do not edit manually. Regenerate with: node scripts/apply_generated_instrument.js");
manifestLines.push("(function() {");
manifestLines.push("  window.SPARK_INSTRUMENT_MANIFEST = [");
instruments.forEach(function(inst, idx) {
  var comma = idx < instruments.length - 1 ? "," : "";
  var sa = inst.scripts.map(function(s) { return q(s); }).join(", ");
  manifestLines.push("    { id: " + q(inst.id) + ", instrument: " + q(inst.instrument) + ", scripts: [" + sa + "] }" + comma);
});
manifestLines.push("  ];");
manifestLines.push("})();");
fs.writeFileSync("js/instruments/instrument_manifest.generated.js", manifestLines.join(NL) + NL);
console.log("  Wrote js/instruments/instrument_manifest.generated.js");

// ── Step 3: Update index.html ──
console.log("");
console.log("Step 3: Updating index.html...");

var html = fs.readFileSync("index.html", "utf8");
var htmlLines = html.split(String.fromCharCode(10));

// Find the instrument block boundaries
var startMarker = "<!-- Instrument Modules -->";
var startIdx = -1, endIdx = -1;
for (var hi = 0; hi < htmlLines.length; hi++) {
  if (htmlLines[hi].indexOf(startMarker) >= 0) startIdx = hi;
  // End at the line BEFORE js/data.js (first non-instrument script after the block)
  if (startIdx >= 0 && endIdx < 0 && htmlLines[hi].indexOf("js/data.js") >= 0) endIdx = hi;
}

if (startIdx >= 0 && endIdx > startIdx) {
  // Build new instrument block
  var newBlock = [];
  newBlock.push(startMarker);
  instruments.forEach(function(inst) {
    newBlock.push("<!-- " + inst.instrument + " -->");
    runtimeScriptsForInstrument(inst).forEach(function(src) {
      newBlock.push("<script data-deferred-src=" + Q + src + Q + "></script>");
    });
  });

  // Replace the block
  var before = htmlLines.slice(0, startIdx);
  var after = htmlLines.slice(endIdx);
  var result = before.concat(newBlock).concat(after);
  fs.writeFileSync("index.html", result.join(NL));
  console.log("  Updated index.html (" + newBlock.length + " lines in instrument block)");
} else {
  console.log("  WARN: Could not find instrument block markers in index.html. Skipping.");
  console.log("  Expected: " + startMarker);
}

// ── Step 4: Update test_curriculum_guardrails.js ──
console.log("");
console.log("Step 4: Updating test file...");

var testPath = "tests/test_curriculum_guardrails.js";
if (fs.existsSync(testPath)) {
  var testCode = fs.readFileSync(testPath, "utf8");
  var changed = false;

  instruments.forEach(function(inst) {
    // Check if register.js is already loaded in test
    var regLine = "js/instruments/" + inst.dir + "/register.js";
    if (testCode.indexOf(regLine) < 0) {
      // Find the "// Load instrument registrations" section and append
      var marker = "// Load instrument registrations";
      var mIdx = testCode.indexOf(marker);
      if (mIdx >= 0) {
        // Find the next blank line after existing registrations
        var searchFrom = mIdx + marker.length;
        var nextBlank = testCode.indexOf(NL + NL, searchFrom);
        if (nextBlank > 0) {
          // No trailing NL on insertLine — the surrounding NL + NL at
          // nextBlank already provides the line break, so an extra NL
          // produces 4 consecutive newlines in the generated test file.
          var insertLine = "safeEval(" + Q + regLine + Q + ");";
          testCode = testCode.slice(0, nextBlank) + NL + insertLine + testCode.slice(nextBlank);
          changed = true;
          console.log("  Added safeEval for " + inst.id + " register.js");
        }
      }
    }

    // Also check for data files in sparksuite layer
    var ssPath = "js/sparksuite/instruments/" + inst.dir;
    if (fs.existsSync(ssPath)) {
      var dataFiles = fs.readdirSync(ssPath).filter(function(f) {
        return f.indexOf("lessons") >= 0 || f.indexOf("skill_tree") >= 0;
      });
      dataFiles.forEach(function(df) {
        var dfPath = ssPath + "/" + df;
        if (testCode.indexOf(dfPath) < 0) {
          var dm = "// Load data files";
          var dIdx = testCode.indexOf(dm);
          if (dIdx >= 0) {
            var ds = dIdx + dm.length;
            var dnb = testCode.indexOf(NL + NL, ds);
            if (dnb > 0) {
              testCode = testCode.slice(0, dnb) + NL + "safeEval(" + Q + dfPath + Q + ");" + testCode.slice(dnb);
              changed = true;
              console.log("  Added safeEval for " + dfPath);
            }
          }
        }
      });
    }
  });

  if (changed) {
    fs.writeFileSync(testPath, testCode);
    console.log("  Updated " + testPath);
  } else {
    console.log("  No changes needed to " + testPath);
  }
} else {
  console.log("  WARN: " + testPath + " not found. Skipping.");
}

// ── Step 5: Run validation ──
if (!skipValidate) {
  console.log("");
  console.log("Step 5: Running validation...");
  console.log("");
  try {
    var cp = require("child_process");
    var result = cp.execSync("node scripts/validate_curriculum.js", { stdio: "inherit" });
  } catch (e) {
    console.log("");
    console.log("Validation completed with failures (see above).");
    console.log("Run: node scripts/suggest_curriculum_fixes.js for fix suggestions.");
  }
} else {
  console.log("");
  console.log("Step 5: Skipped validation (--skip-validate)");
}

console.log("");
console.log("=== Integration Complete ===");
console.log("  Instruments: " + instruments.length);
console.log("  Manifest:    js/instruments/instrument_manifest.generated.js");
console.log("  Index:       index.html");
console.log("  Test:        tests/test_curriculum_guardrails.js");
