#!/usr/bin/env node
var fs = require("fs");
var path = require("path");
var NL = String.fromCharCode(10);
var Q = String.fromCharCode(34);
function q(s) { return Q+s+Q; }

var rtDir = "js/instruments";
var ssDir = "js/sparksuite/instruments";

var dirs = fs.readdirSync(rtDir).filter(function(d) {
  var full = path.join(rtDir, d);
  return fs.statSync(full).isDirectory() && fs.existsSync(path.join(full, "register.js"));
});

function extractField(code, field) { var idx = code.indexOf(field); if (idx < 0) return null; var rest = code.substring(idx + field.length); var m = rest.match(/["']([^"']+)/); return m ? m[1] : null; }
// extractField used instead of regex

var order = ["skill_tree","lessons","exercises","chords","scales","tuning","module","adapter","index"];
var instruments = [];

dirs.forEach(function(dir) {
  var code = fs.readFileSync(path.join(rtDir, dir, "register.js"), "utf8");
  var id = extractField(code, "id:");
  var inst = extractField(code, "instrument:") || dir;
  if (!id) return;
  var scripts = [];
  var ssPath = path.join(ssDir, dir);
  if (fs.existsSync(ssPath)) {
    var ssFiles = fs.readdirSync(ssPath).filter(function(f){return f.endsWith(".js")});
    ssFiles.sort(function(a,b){var ai=99,bi=99;for(var i=0;i<order.length;i++){if(a.indexOf(order[i])>=0)ai=i;if(b.indexOf(order[i])>=0)bi=i}return ai-bi});
    ssFiles.forEach(function(f){ scripts.push(ssDir+"/"+dir+"/"+f); });
  }
  var rtFiles = fs.readdirSync(path.join(rtDir,dir)).filter(function(f){return f.endsWith(".js")});
  rtFiles.sort(function(a,b){if(a==="register.js")return 1;if(b==="register.js")return -1;return a.localeCompare(b)});
  rtFiles.forEach(function(f){ scripts.push(rtDir+"/"+dir+"/"+f); });
  instruments.push({id:id, instrument:inst, scripts:scripts});
});

var out = [];
out.push("// AUTO-GENERATED by apply_generated_instrument.js");
out.push("// Do not edit manually");
out.push("(function() {");
out.push("  window.SPARK_INSTRUMENT_MANIFEST = [");
instruments.forEach(function(inst,idx){
  var comma = idx<instruments.length-1 ? "," : "";
  var sa = inst.scripts.map(function(s){return q(s)}).join(", ");
  out.push("    { id: "+q(inst.id)+", instrument: "+q(inst.instrument)+", scripts: ["+sa+"] }"+comma);
});
out.push("  ];");
out.push("})();");
fs.writeFileSync("js/instruments/instrument_manifest.generated.js", out.join(NL)+NL);
console.log("Manifest rebuilt with " + instruments.length + " instruments");
