(function() {
  var SparkErrorCodes = Object.freeze({
    UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
    SESSION_INVALID: "SESSION_INVALID",
    SESSION_INVALID_EXERCISE_REFERENCE: "SESSION_INVALID_EXERCISE_REFERENCE",
    SESSION_STATE_INVALID_TRANSITION: "SESSION_STATE_INVALID_TRANSITION",
    INSTRUMENT_NOT_REGISTERED: "INSTRUMENT_NOT_REGISTERED",
    INSTRUMENT_CONTRACT_INVALID: "INSTRUMENT_CONTRACT_INVALID",
    CONTENT_INVALID: "CONTENT_INVALID",
    ACTION_HANDLER_MISSING: "ACTION_HANDLER_MISSING",
    ACTION_UNKNOWN: "ACTION_UNKNOWN",
    CHART_LOAD_FAILED: "CHART_LOAD_FAILED",
    AUDIO_CONTEXT_FAILED: "AUDIO_CONTEXT_FAILED",
    INPUT_DEVICE_UNAVAILABLE: "INPUT_DEVICE_UNAVAILABLE",
    STORAGE_READ_FAILED: "STORAGE_READ_FAILED",
    STORAGE_WRITE_FAILED: "STORAGE_WRITE_FAILED",
    SAVE_MIGRATION_FAILED: "SAVE_MIGRATION_FAILED",
    RUNTIME_FRAME_BUDGET_EXCEEDED: "RUNTIME_FRAME_BUDGET_EXCEEDED"
  });

  if (typeof window !== "undefined") {
    window.SparkErrorCodes = SparkErrorCodes;
  }

  if (typeof module !== "undefined") {
    module.exports = {
      SparkErrorCodes: SparkErrorCodes
    };
  }
})();
